[package]
name = "car_logger"
version = "1.1.0"
authors = ["ccfreak2k"]
edition = "2018"

[dependencies]
#async-std = "1.10.0"
chrono = "0.4"
clap = "2.33.3"
gpio = "0.4.1"
hex = "0.4.2"
log = "0.4.11"
socketcan = "1.7"
serde = { version = "1.0.118", features = ["derive"] }
signal-hook = "0.3.4"
tokio = "1.26.0"
toml = "0.5.8"
